export const GET_ALL_DOGS = "GET_ALL_DOGS";
export const CLEAR_DOGS_FILTERS = "CLEAR_DOGS_FILTERS";
export const GET_DOGS_DETAIL = "GET_DOGS_DETAIL";
export const GET_DOG_BY_NAME = "GET_DOG_BY_NAME";

export const FILTER_BY_TEMPEREMENTS = "FILTER_BY_TEMPEREMENTS";
export const GET_DOGS_TEMPEREMENTS = " GET_DOGS_TEMPEREMENTS";
export const FILTER_CREATED = "FILTER_CREATED";
export const ORDER_BY_NAME = "ORDER_BY_NAME";
export const ORDER_BY_WEIGHT = "ORDER_BY_WEIGHT";
